version: '3'
services:
  flask_cicd:
    image: lasanthar78/flask-cicd:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_USERNAME: dummy
